version: 1.0.{build}
os: unstable

platform:
  - x64

environment:
  PACKAGE: ctypes
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64
  MSYS_ROOT: C:\msys64

install:
  - %MSYS_ROOT%\usr\bin\bash -lc "pacman --noconfirm -S mingw/mingw-w64-gobject-introspection mingw/mingw-w64-gtk3"
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
