version: 1.0.{build}
os: unstable

platform:
  - x64

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-gobject-introspection \
                                mingw-w64-gtk3"

  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
