os:
  - linux
  - osx

language: c
dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - env: TYPE=ubuntu-16.04
    - env: TYPE=ubuntu-17.10
    - env: TYPE=ubuntu-18.04
    - env: TYPE=debian-buster
    - env: TYPE=centos-7

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t ocaml-gi/${TYPE} -f travis/Dockerfile.${TYPE} .; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./travis/install-macos-deps .; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --interactive --tty ocaml-gi/${TYPE}; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./travis/run-macos-tests .; fi
